export const ACTION_TYPE = {
  MAKE_BET: "MAKE_BET",
  CLEAR_BET: "CLEAR_BET",
  HIT_ACTION: "HIT_ACTION",
  DEAL_ACTION: "DEAL_ACTION",
  STAY_ACTION: "STAY_ACTION",
  RESET_GAME: "RESET_ACTION",
  CALC_TOTAL: "CALC_TOTAL",
} as const;

export type GameActionType = typeof ACTION_TYPE[keyof typeof ACTION_TYPE];
