export const CARD_LIST = [
  {
    code: "AS",
    image: "http://deckofcardsapi.com/static/img/AS.png",
    suit: "SPADES",
    value: "ACE",
    cardValue: "1",
  },
  {
    code: "2S",
    image: "http://deckofcardsapi.com/static/img/2S.png",
    suit: "SPADES",
    value: "2",
    cardValue: "2",
  },
  {
    code: "3S",
    image: "http://deckofcardsapi.com/static/img/3S.png",
    suit: "SPADES",
    value: "3",
    cardValue: "3",
  },
  {
    code: "4S",
    image: "http://deckofcardsapi.com/static/img/4S.png",
    suit: "SPADES",
    value: "4",
    cardValue: "4",
  },
  {
    code: "5S",
    image: "http://deckofcardsapi.com/static/img/5S.png",
    suit: "SPADES",
    value: "5",
    cardValue: "5",
  },
  {
    code: "6S",
    image: "http://deckofcardsapi.com/static/img/6S.png",
    suit: "SPADES",
    value: "6",
    cardValue: "6",
  },
  {
    code: "7S",
    image: "http://deckofcardsapi.com/static/img/7S.png",
    suit: "SPADES",
    value: "7",
    cardValue: "7",
  },
  {
    code: "8S",
    image: "http://deckofcardsapi.com/static/img/8S.png",
    suit: "SPADES",
    value: "8",
    cardValue: "8",
  },
  {
    code: "9S",
    image: "http://deckofcardsapi.com/static/img/9S.png",
    suit: "SPADES",
    value: "9",
    cardValue: "9",
  },
  {
    code: "0S",
    image: "http://deckofcardsapi.com/static/img/0S.png",
    suit: "SPADES",
    value: "10",
    cardValue: "10",
  },
  {
    code: "JS",
    image: "http://deckofcardsapi.com/static/img/JS.png",
    suit: "SPADES",
    value: "JACK",
    cardValue: "10",
  },
  {
    code: "QS",
    image: "http://deckofcardsapi.com/static/img/QS.png",
    suit: "SPADES",
    value: "QUEEN",
    cardValue: "10",
  },
  {
    code: "KS",
    image: "http://deckofcardsapi.com/static/img/KS.png",
    suit: "SPADES",
    value: "KING",
    cardValue: "10",
  },
  {
    code: "AD",
    image: "http://deckofcardsapi.com/static/img/aceDiamonds.png",
    suit: "DIAMONDS",
    value: "ACE",
    cardValue: "1",
  },
  {
    code: "2D",
    image: "http://deckofcardsapi.com/static/img/2D.png",
    suit: "DIAMONDS",
    value: "2",
    cardValue: "2",
  },
  {
    code: "3D",
    image: "http://deckofcardsapi.com/static/img/3D.png",
    suit: "DIAMONDS",
    value: "3",
    cardValue: "3",
  },
  {
    code: "4D",
    image: "http://deckofcardsapi.com/static/img/4D.png",
    suit: "DIAMONDS",
    value: "4",
    cardValue: "4",
  },
  {
    code: "5D",
    image: "http://deckofcardsapi.com/static/img/5D.png",
    suit: "DIAMONDS",
    value: "5",
    cardValue: "5",
  },
  {
    code: "6D",
    image: "http://deckofcardsapi.com/static/img/6D.png",
    suit: "DIAMONDS",
    value: "6",
    cardValue: "6",
  },
  {
    code: "7D",
    image: "http://deckofcardsapi.com/static/img/7D.png",
    suit: "DIAMONDS",
    value: "7",
    cardValue: "7",
  },
  {
    code: "8D",
    image: "http://deckofcardsapi.com/static/img/8D.png",
    suit: "DIAMONDS",
    value: "8",
    cardValue: "8",
  },
  {
    code: "9D",
    image: "http://deckofcardsapi.com/static/img/9D.png",
    suit: "DIAMONDS",
    value: "9",
    cardValue: "9",
  },
  {
    code: "0D",
    image: "http://deckofcardsapi.com/static/img/0D.png",
    suit: "DIAMONDS",
    value: "10",
    cardValue: "10",
  },
  {
    code: "JD",
    image: "http://deckofcardsapi.com/static/img/JD.png",
    suit: "DIAMONDS",
    value: "JACK",
    cardValue: "10",
  },
  {
    code: "QD",
    image: "http://deckofcardsapi.com/static/img/QD.png",
    suit: "DIAMONDS",
    value: "QUEEN",
    cardValue: "10",
  },
  {
    code: "KD",
    image: "http://deckofcardsapi.com/static/img/KD.png",
    suit: "DIAMONDS",
    value: "KING",
    cardValue: "10",
  },
  {
    code: "AC",
    image: "http://deckofcardsapi.com/static/img/AC.png",
    suit: "CLUBS",
    value: "ACE",
    cardValue: "1",
  },
  {
    code: "2C",
    image: "http://deckofcardsapi.com/static/img/2C.png",
    suit: "CLUBS",
    value: "2",
    cardValue: "2",
  },
  {
    code: "3C",
    image: "http://deckofcardsapi.com/static/img/3C.png",
    suit: "CLUBS",
    value: "3",
    cardValue: "3",
  },
  {
    code: "4C",
    image: "http://deckofcardsapi.com/static/img/4C.png",
    suit: "CLUBS",
    value: "4",
    cardValue: "4",
  },
  {
    code: "5C",
    image: "http://deckofcardsapi.com/static/img/5C.png",
    suit: "CLUBS",
    value: "5",
    cardValue: "5",
  },
  {
    code: "6C",
    image: "http://deckofcardsapi.com/static/img/6C.png",
    suit: "CLUBS",
    value: "6",
    cardValue: "6",
  },
  {
    code: "7C",
    image: "http://deckofcardsapi.com/static/img/7C.png",
    suit: "CLUBS",
    value: "7",
    cardValue: "7",
  },
  {
    code: "8C",
    image: "http://deckofcardsapi.com/static/img/8C.png",
    suit: "CLUBS",
    value: "8",
    cardValue: "8",
  },
  {
    code: "9C",
    image: "http://deckofcardsapi.com/static/img/9C.png",
    suit: "CLUBS",
    value: "9",
    cardValue: "9",
  },
  {
    code: "0C",
    image: "http://deckofcardsapi.com/static/img/0C.png",
    suit: "CLUBS",
    value: "10",
    cardValue: "10",
  },
  {
    code: "JC",
    image: "http://deckofcardsapi.com/static/img/JC.png",
    suit: "CLUBS",
    value: "JACK",
    cardValue: "10",
  },
  {
    code: "QC",
    image: "http://deckofcardsapi.com/static/img/QC.png",
    suit: "CLUBS",
    value: "QUEEN",
    cardValue: "10",
  },
  {
    code: "KC",
    image: "http://deckofcardsapi.com/static/img/KC.png",
    suit: "CLUBS",
    value: "KING",
    cardValue: "10",
  },
  {
    code: "AH",
    image: "http://deckofcardsapi.com/static/img/AH.png",
    suit: "HEARTS",
    value: "ACE",
    cardValue: "1",
  },
  {
    code: "2H",
    image: "http://deckofcardsapi.com/static/img/2H.png",
    suit: "HEARTS",
    value: "2",
    cardValue: "2",
  },
  {
    code: "3H",
    image: "http://deckofcardsapi.com/static/img/3H.png",
    suit: "HEARTS",
    value: "3",
    cardValue: "3",
  },
  {
    code: "4H",
    image: "http://deckofcardsapi.com/static/img/4H.png",
    suit: "HEARTS",
    value: "4",
    cardValue: "4",
  },
  {
    code: "5H",
    image: "http://deckofcardsapi.com/static/img/5H.png",
    suit: "HEARTS",
    value: "5",
    cardValue: "5",
  },
  {
    code: "6H",
    image: "http://deckofcardsapi.com/static/img/6H.png",
    suit: "HEARTS",
    value: "6",
    cardValue: "6",
  },
  {
    code: "7H",
    image: "http://deckofcardsapi.com/static/img/7H.png",
    suit: "HEARTS",
    value: "7",
    cardValue: "7",
  },
  {
    code: "8H",
    image: "http://deckofcardsapi.com/static/img/8H.png",
    suit: "HEARTS",
    value: "8",
    cardValue: "8",
  },
  {
    code: "9H",
    image: "http://deckofcardsapi.com/static/img/9H.png",
    suit: "HEARTS",
    value: "9",
    cardValue: "9",
  },
  {
    code: "0H",
    image: "http://deckofcardsapi.com/static/img/0H.png",
    suit: "HEARTS",
    value: "10",
    cardValue: "10",
  },
  {
    code: "JH",
    image: "http://deckofcardsapi.com/static/img/JH.png",
    suit: "HEARTS",
    value: "JACK",
    cardValue: "10",
  },
  {
    code: "QH",
    image: "http://deckofcardsapi.com/static/img/QH.png",
    suit: "HEARTS",
    cardValue: "10",
    value: "QUEEN",
  },
  {
    code: "KH",
    image: "http://deckofcardsapi.com/static/img/KH.png",
    suit: "HEARTS",
    value: "KING",
    cardValue: "10",
  },
]
